name: deploy

on:
  push:
    tags:
      - '*'

jobs:

  # Build executable Jar files and package as a Release
  deploy-release:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
     
      - uses: actions/setup-java@v3
        with:
          java-version: "18"
          architecture: x64
          distribution: 'temurin'
          cache: 'maven'

      - name: Create the (jar) packages and libraries
        run: mvn clean package -Dskiptest -Pproduction

      - name: Get version
        id: tagName
        run: |
          VERSION=$(cat ./VERSION)
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Zip file
        run: |
          ARCHIVE_NAME="privacydashboard-${{ steps.tagName.outputs.tag }}"
          ARCHIVE_FILE="${ARCHIVE_NAME}.zip"
          zip -r ${ARCHIVE_FILE} privacydashboard/target/classes
          zip -r ${ARCHIVE_FILE} privacydashboard/target/flow-frontend


      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.tagName.outputs.tag }}
          files: |
            ./*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

